// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs2WjWohRrf5jCY907AJ94fmgkpUhMgE8',
    appId: '1:314873333725:web:8d12309a38c19153989834',
    messagingSenderId: '314873333725',
    projectId: 'teste-6005e',
    authDomain: 'teste-6005e.firebaseapp.com',
    storageBucket: 'teste-6005e.firebasestorage.app',
    measurementId: 'G-DCWP5Z5CEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-4uQJbVkLYcWHosIIwgSIWIOWP-FXVU',
    appId: '1:314873333725:android:cdadd13901b0d819989834',
    messagingSenderId: '314873333725',
    projectId: 'teste-6005e',
    storageBucket: 'teste-6005e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIzNu5KcchGPmamEsfZ9lmEafJF2DcIyo',
    appId: '1:314873333725:ios:d275c8737895cfdf989834',
    messagingSenderId: '314873333725',
    projectId: 'teste-6005e',
    storageBucket: 'teste-6005e.firebasestorage.app',
    iosBundleId: 'com.example.cadastro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIzNu5KcchGPmamEsfZ9lmEafJF2DcIyo',
    appId: '1:314873333725:ios:d275c8737895cfdf989834',
    messagingSenderId: '314873333725',
    projectId: 'teste-6005e',
    storageBucket: 'teste-6005e.firebasestorage.app',
    iosBundleId: 'com.example.cadastro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs2WjWohRrf5jCY907AJ94fmgkpUhMgE8',
    appId: '1:314873333725:web:8d12309a38c19153989834',
    messagingSenderId: '314873333725',
    projectId: 'teste-6005e',
    authDomain: 'teste-6005e.firebaseapp.com',
    storageBucket: 'teste-6005e.firebasestorage.app',
    measurementId: 'G-DCWP5Z5CEL',
  );
}
