// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH2Ytoub6WaexiGu_nCUq_LlM_dMFBmCo',
    appId: '1:840040907500:web:bf93730be96e9a59889bc9',
    messagingSenderId: '840040907500',
    projectId: 'neuroway-7c999',
    authDomain: 'neuroway-7c999.firebaseapp.com',
    storageBucket: 'neuroway-7c999.firebasestorage.app',
    measurementId: 'G-4PR54FC0RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SmkCAjA_83NletqZBFyEjP1u5llaq-E',
    appId: '1:840040907500:android:7e2b769ff3d95ac7889bc9',
    messagingSenderId: '840040907500',
    projectId: 'neuroway-7c999',
    storageBucket: 'neuroway-7c999.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxYekqY9qCi9N1vwWXnzkeD9Lpyj7aqw',
    appId: '1:840040907500:ios:bd60a3c8aac4818b889bc9',
    messagingSenderId: '840040907500',
    projectId: 'neuroway-7c999',
    storageBucket: 'neuroway-7c999.firebasestorage.app',
    iosBundleId: 'com.example.neuroway',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxYekqY9qCi9N1vwWXnzkeD9Lpyj7aqw',
    appId: '1:840040907500:ios:bd60a3c8aac4818b889bc9',
    messagingSenderId: '840040907500',
    projectId: 'neuroway-7c999',
    storageBucket: 'neuroway-7c999.firebasestorage.app',
    iosBundleId: 'com.example.neuroway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH2Ytoub6WaexiGu_nCUq_LlM_dMFBmCo',
    appId: '1:840040907500:web:8db835c6e3fef44e889bc9',
    messagingSenderId: '840040907500',
    projectId: 'neuroway-7c999',
    authDomain: 'neuroway-7c999.firebaseapp.com',
    storageBucket: 'neuroway-7c999.firebasestorage.app',
    measurementId: 'G-25K0EWBLGH',
  );
}
